import Soup from "assets/images/recipe-images/soup.png";
import BeefStew from "assets/images/recipe-images/beef-stew.jpeg";
import Salmon from "assets/images/recipe-images/salmon.jpeg";
import Salad from "assets/images/recipe-images/salad.jpeg";
import Risotto from "assets/images/recipe-images/risotto.jpeg";
import LambChops from "assets/images/recipe-images/lamb-chops.jpeg";

export const RECIPIES = [
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Beef Stew",
      id: "3721893793123213",
      time: [null, 50],
      image: BeefStew,
      price: 0.23,
      rating: 4,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Beef Stew",
      id: "3721893793123213",
      time: [null, 50],
      image: BeefStew,
      price: 0.23,
      rating: 4,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Salmon",
      id: "dsnahkldsahlksad",
      time: [1, null],
      image: Salmon,
      price: 4,
      rating: 5,
      origin: "spain",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Salad",
      id: "jfeufnwfiowuhui",
      time: [3, null],
      image: Salad,
      price: 1.48,
      rating: 4,
      origin: "japan",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",

      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Risotto",
      id: "32rkjl32jk",
      time: [null, 20],
      image: Risotto,
      price: 8.3,
      rating: 3,
      origin: "usa",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Lamb Chops",
      id: "dajsld",
      time: [2, null],
      image: LambChops,
      price: 2.82,
      rating: 1,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      link: "",
    },
    ingredients: {
      vegetables: [
        [1, "", "onion"],
        [2, "", "carrot"],
        [null, "", "spinach"],
        [1, "", "squash"],
      ],
      herbsAndSpices: [
        [2, "", "onion"],
        [null, "", "thyme"],
        [null, "", "cumin seeds"],
      ],
      carbohydrates: [[2, "", "sweet potatoes"]],
      other: [
        [null, "", "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
];
