import Soup from "assets/images/recipe-images/soup.png";
import BeefStew from "assets/images/recipe-images/beef-stew.jpeg";
import Salmon from "assets/images/recipe-images/salmon.jpeg";
import Salad from "assets/images/recipe-images/salad.jpeg";
import Risotto from "assets/images/recipe-images/risotto.jpeg";
import LambChops from "assets/images/recipe-images/lamb-chops.jpeg";

export const RECIPIES = [
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e78fdsfs9exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: false,
      source: {
        type: "book",
        value:
          "Learn Japanese Cooking 101 - The Best Cooking Book in the World!",
      },
    },
    ingredients: {
      fruitVeg: [
        [
          1,
          null,
          "onion lfbsdkjfdskjdsfhf hfkjdshf jkhfk hfjkds hfdjsfhdskj fdsk hfkjdsf fjsdkl",
        ],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen stuff"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "some oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water. Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutesPut in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes ",
      "Boil water. Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutesPut in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes Put in the oven and cook for 20 minutes ",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: [
      "Boil the water before cutting the vegetables Boil the water before cutting the vegetables Boil the water before cutting the vegetables Boil the water before cutting the vegetables Boil the water before cutting the vegetables Boil the water before cutting the vegetables Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
      "Boil the water before cutting the vegetables",
    ],
    tags: [
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
      "healthy",
      "soup",
      "vegetables",
    ],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y2922",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1fsfsdsfy2922",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo211y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789ekfldxo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e7fdsnkl89exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e7dsds89exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e7fdjflksk89exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781efjfjff789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789e222xo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Beef Stew",
      id: "3721893793123213",
      time: [null, 50],
      image: BeefStew,
      price: 0.23,
      rating: 4,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Tomato Soup with bread, cream and some other ingredients",
      id: "exh781e789exo1y29",
      image: Soup,
      time: [1, 30],
      price: 9.12,
      rating: 2,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water.",
      "Cut two onions and add to frying pan?",
      "Add the garlic and stir!",
      "Put in the oven and cook for 20 minutes.",
      "Boil water",
      "Cut two onions and add to frying pan.",
      "Add the garlic and stir.",
      "Put in the oven and cook for 20 minutes!",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Beef Stew",
      id: "37218937214jlk93123213",
      time: [null, 50],
      image: BeefStew,
      price: 0.23,
      rating: 4,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Salmon",
      id: "dsnahkldsahlksad",
      time: [1, null],
      image: Salmon,
      price: 4,
      rating: 5,
      servings: 3,
      origin: "spain",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Salad",
      id: "jfeufnwfiowuhui",
      time: [3, null],
      image: Salad,
      price: 1.48,
      rating: 4,
      servings: 3,
      origin: "japan",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",

      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Risotto",
      id: "32rkjl32jk",
      time: [null, 20],
      image: Risotto,
      price: 8.3,
      rating: 3,
      servings: 3,
      origin: "usa",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
  {
    overview: {
      title: "Lamb Chops",
      id: "dajsld",
      time: [2, null],
      image: LambChops,
      price: 2.82,
      rating: 1,
      servings: 3,
      origin: "uk",
      vegetarian: true,
      vegan: true,
      source: { type: "link", value: "" },
    },
    ingredients: {
      fruitVeg: [
        [1, null, "onion"],
        [2, null, "carrot"],
        [null, null, "spinach"],
        [1, null, "squash"],
      ],
      dairy: [[500, "g", "dairy"]],
      frozen: [[500, "g", "frozen"]],
      nutsDried: [[2, "g", "peanuts"]],
      saucesOil: [[200, "ml", "oil"]],
      sweetsChocolate: [[200, "ml", "oil"]],
      meatFish: [[500, "g", "fish"]],
      tinnedGoods: [[500, "g", "tinned tuna"]],
      herbsSpices: [
        [2, null, "basil"],
        [null, null, "thyme"],
        [null, null, "cumin seeds"],
      ],
      carbohydrates: [[2, null, "sweet potatoes"]],
      other: [
        [null, null, "vegetable stock"],
        [500, "g", "vegetable stock"],
      ],
    },
    steps: [
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
      "Add the garlic and stir",
      "Put in the oven and cook for 20 minutes",
      "Boil water",
      "Cut two onions and add to frying pan",
    ],
    tips: ["Boil the water before cutting the vegetables"],
    tags: ["healthy", "soup", "vegetables"],
  },
];
